services:
  app:
    build:
      dockerfile: Dockerfile
      target: development
    container_name: dev-tunnel
    ports:
      - "2222:2222"
    environment:
      - HOST_PROJECT_PATH=${PWD}
    volumes:
      - ./:/app
    tty: true
    stdin_open: true