services:
  app:
    build:
      context: .
      target: production
    container_name: dev-tunnel
    # Adicione este bloco:
    environment:
      - HOST_PROJECT_PATH=${PWD}
    ports:
      - "2222:2222"
    volumes:
      - ./.dev_tunnel:/app/.dev_tunnel
    tty: true
    stdin_open: true